"""empty message

Revision ID: 359eae2ef726
Revises: 2f345e88e94c
Create Date: 2024-01-21 18:47:02.566408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359eae2ef726'
down_revision = '2f345e88e94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('clients_address_id_fkey', type_='foreignkey')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('clients_address_id_fkey', 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###
