"""empty message

Revision ID: 9a3641939685
Revises: deb94660fa59
Create Date: 2024-01-29 13:45:14.617102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3641939685'
down_revision = 'deb94660fa59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint(None, ['client_id'])
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
