"""cart_model

Revision ID: ddb2cd879695
Revises: af78d866902d
Create Date: 2024-01-26 16:11:07.291801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb2cd879695'
down_revision = 'af78d866902d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_client_id_key', type_='unique')
        batch_op.drop_constraint('cart_client_id_fkey', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('cart_client_id_fkey', 'clients', ['client_id'], ['id'])
        batch_op.create_unique_constraint('cart_client_id_key', ['client_id'])

    # ### end Alembic commands ###
